### ISSUE TITLE
Unable to find instrumentation info for: ComponentInfo{com.example.android.perf.test/android.support.test.runner.AndroidJUnitRunner}

### ISSUE THREAD

**Issue by David-Kuper** [googlesamples/android-constraint-layout-performance#4]
when I run the run.sh file. I get an error  : 
`Unable to find instrumentation info for: ComponentInfo{com.example.android.perf.test/android.support.test.runner.AndroidJUnitRunner}`

how can I fix the problem, thanks.

**Comment by thagikura** [comment]
I think you need to install the Android Sdk and set ANDROID_HOME appropriately. The class is part of the Android Sdk.

**Comment by tp7309** [comment]
Missing install `*AndroidTest.apk`.
1. run `./gradlew assembleAndroidTest`.
2. `adb install -r app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk`
3. retry `./run.sh device_id`.
